### PR TITLE
Wordpress login support

### PR DESCRIPTION
**Pull request by simahero**
### Dear UsefulTeam!

I am not sure, how this plugin gonna change over the time.
I tought these features would be best implemented in the plugin itself.

**Adding Wordpress login support**

1. Via setting a cookie - filter: _jwt_set_cookie_
2. Via performing an action - filter: _jwt_do_hook_ , action: _jwt_wp_login_

### CODE REVIEW

**Review by contactjavas — COMMENTED** [review]
Hi @simahero , thanks for submitting the PR.

Would you mind to explain more about your use-case? Like, why do you need to set a login cookie? This plugin was intended to work with REST, not a regular wp-admin login.

**Comment by sun** [comment]
I agree, the regular login cookies are a different authentication concept. They should not be mixed with a token based authentication flow.

The closest to this are so called refresh tokens. I am implementing them currently in #33. Probably ready for merge and usage at the end of this month.

Refresh tokens allow clients to create new access tokens without storing the user login credentials on the client-side upon initial login. Maybe that is what you are looking for instead?

**Comment by contactjavas** [comment]
Agree with @sun . Sorry, let me close this PR @simahero :)

**Comment by simahero** [comment]
This was a usecase, I do not even remeber. Simple ```do_action()``` hooks would be appreciated imo!

**Pull request closed without merging**
